job_name: atlas_capture_test

device_type: docker
tags:
- inet

visibility: public

timeouts:
  job:
    seconds: 600
  action:
    seconds: 600

actions:

- deploy:
    to: docker
    image:
        name: vav_test_image
        local: true

- boot:
    method: docker
    command: "ls -l"

- test:
    timeout:
      seconds: 600

    monitor:
    - name: test1
      prompts: [ "=>", "/ # "]
      script:
      - command: "ls -l"
        #successes:
        #- message: "Giving up"  # Adjust this based on what you consider a successful result or handle retries.
      # Ensure proper output display by setting echo: true

      #echo: discard
      #script:
      #- command: "capture"
        #successes:
       # - message: "retry"

